controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

handle-form:
    path: /
    controller: App\Controller\ReportFormController::handleForm
    methods: [GET, POST]